//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид операции.
    /// </summary>
    //  *** Start programmer edit section *** (ВидОперации CustomAttributes)

    //  *** End programmer edit section *** (ВидОперации CustomAttributes)
    [AutoAltered()]
    [Caption("Вид операции")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидОперацииE", new string[] {
            "Наименование as \'Наименование\'",
            "Актуально as \'Актуально\'"})]
    [View("ВидОперацииL", new string[] {
            "Наименование as \'Наименование\'",
            "Актуально as \'Актуально\'"})]
    public class ВидОперации : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private bool fАктуально;
        
        //  *** Start programmer edit section *** (ВидОперации CustomMembers)

        //  *** End programmer edit section *** (ВидОперации CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (ВидОперации.Наименование CustomAttributes)

        //  *** End programmer edit section *** (ВидОперации.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (ВидОперации.Наименование Get start)

                //  *** End programmer edit section *** (ВидОперации.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (ВидОперации.Наименование Get end)

                //  *** End programmer edit section *** (ВидОперации.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ВидОперации.Наименование Set start)

                //  *** End programmer edit section *** (ВидОперации.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (ВидОперации.Наименование Set end)

                //  *** End programmer edit section *** (ВидОперации.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        //  *** Start programmer edit section *** (ВидОперации.Актуально CustomAttributes)

        //  *** End programmer edit section *** (ВидОперации.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                //  *** Start programmer edit section *** (ВидОперации.Актуально Get start)

                //  *** End programmer edit section *** (ВидОперации.Актуально Get start)
                bool result = this.fАктуально;
                //  *** Start programmer edit section *** (ВидОперации.Актуально Get end)

                //  *** End programmer edit section *** (ВидОперации.Актуально Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ВидОперации.Актуально Set start)

                //  *** End programmer edit section *** (ВидОперации.Актуально Set start)
                this.fАктуально = value;
                //  *** Start programmer edit section *** (ВидОперации.Актуально Set end)

                //  *** End programmer edit section *** (ВидОперации.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидОперацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидОперацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидОперацииE", typeof(IIS.WebLearning2016.ВидОперации));
                }
            }
            
            /// <summary>
            /// "ВидОперацииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидОперацииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидОперацииL", typeof(IIS.WebLearning2016.ВидОперации));
                }
            }
        }
    }
}
