//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оператор.
    /// </summary>
    //  *** Start programmer edit section *** (Оператор CustomAttributes)

    //  *** End programmer edit section *** (Оператор CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОператорE", new string[] {
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "Должность.Наименование"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("ОператорE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ОператорL", new string[] {
            "ФИО as \'ФИО\'",
            "Должность",
            "Должность.Наименование as \'Должность\'"}, Hidden=new string[] {
            "Должность"})]
    public class Оператор : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.WebLearning2016.Должность fДолжность;
        
        //  *** Start programmer edit section *** (Оператор CustomMembers)

        //  *** End programmer edit section *** (Оператор CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (Оператор.ФИО CustomAttributes)

        //  *** End programmer edit section *** (Оператор.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (Оператор.ФИО Get start)

                //  *** End programmer edit section *** (Оператор.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (Оператор.ФИО Get end)

                //  *** End programmer edit section *** (Оператор.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Оператор.ФИО Set start)

                //  *** End programmer edit section *** (Оператор.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (Оператор.ФИО Set end)

                //  *** End programmer edit section *** (Оператор.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Оператор.
        /// </summary>
        //  *** Start programmer edit section *** (Оператор.Должность CustomAttributes)

        //  *** End programmer edit section *** (Оператор.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.WebLearning2016.Должность Должность
        {
            get
            {
                //  *** Start programmer edit section *** (Оператор.Должность Get start)

                //  *** End programmer edit section *** (Оператор.Должность Get start)
                IIS.WebLearning2016.Должность result = this.fДолжность;
                //  *** Start programmer edit section *** (Оператор.Должность Get end)

                //  *** End programmer edit section *** (Оператор.Должность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Оператор.Должность Set start)

                //  *** End programmer edit section *** (Оператор.Должность Set start)
                this.fДолжность = value;
                //  *** Start programmer edit section *** (Оператор.Должность Set end)

                //  *** End programmer edit section *** (Оператор.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОператорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОператорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОператорE", typeof(IIS.WebLearning2016.Оператор));
                }
            }
            
            /// <summary>
            /// "ОператорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОператорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОператорL", typeof(IIS.WebLearning2016.Оператор));
                }
            }
        }
    }
}
