//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Операция.
    /// </summary>
    //  *** Start programmer edit section *** (Операция CustomAttributes)

    //  *** End programmer edit section *** (Операция CustomAttributes)
    [BusinessServer("IIS.WebLearning2016.ОперацияBS, WebLearning2016.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОперацияE", new string[] {
            "ДолжностьОператораСтр",
            "Дата",
            "ВидОперации as \'Вид операции\'",
            "ВидОперации.Наименование",
            "Оператор.ФИО",
            "Оператор.Должность",
            "Оператор.Должность.Наименование",
            "Оператор as \'Оператор\'",
            "Клиент.Наименование",
            "Клиент as \'Клиент\'",
            "МестоВОчереди.Номер",
            "МестоВОчереди.ОчередьСтр",
            "МестоВОчереди.Очередь",
            "МестоВОчереди.Очередь.Наименование",
            "МестоВОчереди.Клиент",
            "МестоВОчереди.Клиент.Наименование",
            "МестоВОчереди as \'Очередь\'",
            "Выполнена"}, Hidden=new string[] {
            "ВидОперации.Наименование",
            "Оператор.ФИО",
            "Оператор.Должность",
            "Оператор.Должность.Наименование",
            "Клиент.Наименование",
            "МестоВОчереди.Номер",
            "МестоВОчереди.ОчередьСтр",
            "МестоВОчереди.Очередь",
            "МестоВОчереди.Очередь.Наименование",
            "МестоВОчереди.Клиент",
            "МестоВОчереди.Клиент.Наименование"})]
    [MasterViewDefineAttribute("ОперацияE", "ВидОперации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОперацияE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОперацияE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОперацияE", "МестоВОчереди", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ОчередьСтр")]
    [View("ОперацияL", new string[] {
            "ДолжностьОператораСтр as \'Должность оператора\'",
            "Дата",
            "ВидОперации",
            "ВидОперации.Наименование as \'Вид операции\'",
            "Оператор.ФИО",
            "Оператор.Должность",
            "Оператор.Должность.Наименование",
            "Оператор as \'Оператор\'",
            "Клиент.Наименование",
            "Клиент as \'Клиент\'",
            "МестоВОчереди.Номер",
            "МестоВОчереди.ОчередьСтр",
            "МестоВОчереди.Очередь",
            "МестоВОчереди.Очередь.Наименование",
            "МестоВОчереди.Клиент",
            "МестоВОчереди.Клиент.Наименование",
            "МестоВОчереди as \'Очередь\'",
            "Выполнена as \'Выполнена\'"}, Hidden=new string[] {
            "ВидОперации",
            "Оператор.ФИО",
            "Оператор.Должность",
            "Оператор.Должность.Наименование",
            "Клиент.Наименование",
            "МестоВОчереди.Номер",
            "МестоВОчереди.ОчередьСтр",
            "МестоВОчереди.Очередь",
            "МестоВОчереди.Очередь.Наименование",
            "МестоВОчереди.Клиент",
            "МестоВОчереди.Клиент.Наименование"})]
    [MasterViewDefineAttribute("ОперацияL", "ВидОперации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОперацияL", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОперацияL", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОперацияL", "МестоВОчереди", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ОчередьСтр")]
    public class Операция : ICSSoft.STORMNET.DataObject
    {
        
        private string fДолжностьОператораСтр;
        
        private System.DateTime fДата;
        
        private string fПредставительСтр;
        
        private bool fВыполнена;
        
        private IIS.WebLearning2016.Оператор fОператор;
        
        private IIS.WebLearning2016.ВидОперации fВидОперации;
        
        private IIS.WebLearning2016.МестоВОчереди fМестоВОчереди;
        
        private IIS.WebLearning2016.Клиент fПредставительКлиента;
        
        private IIS.WebLearning2016.Клиент fКлиент;
        
        //  *** Start programmer edit section *** (Операция CustomMembers)

        //  *** End programmer edit section *** (Операция CustomMembers)

        
        /// <summary>
        /// ДолжностьОператораСтр.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.ДолжностьОператораСтр CustomAttributes)

        //  *** End programmer edit section *** (Операция.ДолжностьОператораСтр CustomAttributes)
        [StrLen(255)]
        public virtual string ДолжностьОператораСтр
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.ДолжностьОператораСтр Get start)

                //  *** End programmer edit section *** (Операция.ДолжностьОператораСтр Get start)
                string result = this.fДолжностьОператораСтр;
                //  *** Start programmer edit section *** (Операция.ДолжностьОператораСтр Get end)

                //  *** End programmer edit section *** (Операция.ДолжностьОператораСтр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.ДолжностьОператораСтр Set start)

                //  *** End programmer edit section *** (Операция.ДолжностьОператораСтр Set start)
                this.fДолжностьОператораСтр = value;
                //  *** Start programmer edit section *** (Операция.ДолжностьОператораСтр Set end)

                //  *** End programmer edit section *** (Операция.ДолжностьОператораСтр Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.Дата CustomAttributes)

        //  *** End programmer edit section *** (Операция.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.Дата Get start)

                //  *** End programmer edit section *** (Операция.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (Операция.Дата Get end)

                //  *** End programmer edit section *** (Операция.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.Дата Set start)

                //  *** End programmer edit section *** (Операция.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (Операция.Дата Set end)

                //  *** End programmer edit section *** (Операция.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПредставительСтр.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.ПредставительСтр CustomAttributes)

        //  *** End programmer edit section *** (Операция.ПредставительСтр CustomAttributes)
        [StrLen(255)]
        public virtual string ПредставительСтр
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.ПредставительСтр Get start)

                //  *** End programmer edit section *** (Операция.ПредставительСтр Get start)
                string result = this.fПредставительСтр;
                //  *** Start programmer edit section *** (Операция.ПредставительСтр Get end)

                //  *** End programmer edit section *** (Операция.ПредставительСтр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.ПредставительСтр Set start)

                //  *** End programmer edit section *** (Операция.ПредставительСтр Set start)
                this.fПредставительСтр = value;
                //  *** Start programmer edit section *** (Операция.ПредставительСтр Set end)

                //  *** End programmer edit section *** (Операция.ПредставительСтр Set end)
            }
        }
        
        /// <summary>
        /// Выполнена.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.Выполнена CustomAttributes)

        //  *** End programmer edit section *** (Операция.Выполнена CustomAttributes)
        public virtual bool Выполнена
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.Выполнена Get start)

                //  *** End programmer edit section *** (Операция.Выполнена Get start)
                bool result = this.fВыполнена;
                //  *** Start programmer edit section *** (Операция.Выполнена Get end)

                //  *** End programmer edit section *** (Операция.Выполнена Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.Выполнена Set start)

                //  *** End programmer edit section *** (Операция.Выполнена Set start)
                this.fВыполнена = value;
                //  *** Start programmer edit section *** (Операция.Выполнена Set end)

                //  *** End programmer edit section *** (Операция.Выполнена Set end)
            }
        }
        
        /// <summary>
        /// Операция.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.Оператор CustomAttributes)

        //  *** End programmer edit section *** (Операция.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual IIS.WebLearning2016.Оператор Оператор
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.Оператор Get start)

                //  *** End programmer edit section *** (Операция.Оператор Get start)
                IIS.WebLearning2016.Оператор result = this.fОператор;
                //  *** Start programmer edit section *** (Операция.Оператор Get end)

                //  *** End programmer edit section *** (Операция.Оператор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.Оператор Set start)

                //  *** End programmer edit section *** (Операция.Оператор Set start)
                this.fОператор = value;
                //  *** Start programmer edit section *** (Операция.Оператор Set end)

                //  *** End programmer edit section *** (Операция.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Операция.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.ВидОперации CustomAttributes)

        //  *** End programmer edit section *** (Операция.ВидОперации CustomAttributes)
        [PropertyStorage(new string[] {
                "ВидОперации"})]
        [NotNull()]
        public virtual IIS.WebLearning2016.ВидОперации ВидОперации
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.ВидОперации Get start)

                //  *** End programmer edit section *** (Операция.ВидОперации Get start)
                IIS.WebLearning2016.ВидОперации result = this.fВидОперации;
                //  *** Start programmer edit section *** (Операция.ВидОперации Get end)

                //  *** End programmer edit section *** (Операция.ВидОперации Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.ВидОперации Set start)

                //  *** End programmer edit section *** (Операция.ВидОперации Set start)
                this.fВидОперации = value;
                //  *** Start programmer edit section *** (Операция.ВидОперации Set end)

                //  *** End programmer edit section *** (Операция.ВидОперации Set end)
            }
        }
        
        /// <summary>
        /// Операция.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.МестоВОчереди CustomAttributes)

        //  *** End programmer edit section *** (Операция.МестоВОчереди CustomAttributes)
        [PropertyStorage(new string[] {
                "МестоВОчереди"})]
        public virtual IIS.WebLearning2016.МестоВОчереди МестоВОчереди
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.МестоВОчереди Get start)

                //  *** End programmer edit section *** (Операция.МестоВОчереди Get start)
                IIS.WebLearning2016.МестоВОчереди result = this.fМестоВОчереди;
                //  *** Start programmer edit section *** (Операция.МестоВОчереди Get end)

                //  *** End programmer edit section *** (Операция.МестоВОчереди Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.МестоВОчереди Set start)

                //  *** End programmer edit section *** (Операция.МестоВОчереди Set start)
                this.fМестоВОчереди = value;
                //  *** Start programmer edit section *** (Операция.МестоВОчереди Set end)

                //  *** End programmer edit section *** (Операция.МестоВОчереди Set end)
            }
        }
        
        /// <summary>
        /// Операция.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.ПредставительКлиента CustomAttributes)

        //  *** End programmer edit section *** (Операция.ПредставительКлиента CustomAttributes)
        [PropertyStorage(new string[] {
                "ПредставительКлиента"})]
        public virtual IIS.WebLearning2016.Клиент ПредставительКлиента
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.ПредставительКлиента Get start)

                //  *** End programmer edit section *** (Операция.ПредставительКлиента Get start)
                IIS.WebLearning2016.Клиент result = this.fПредставительКлиента;
                //  *** Start programmer edit section *** (Операция.ПредставительКлиента Get end)

                //  *** End programmer edit section *** (Операция.ПредставительКлиента Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.ПредставительКлиента Set start)

                //  *** End programmer edit section *** (Операция.ПредставительКлиента Set start)
                this.fПредставительКлиента = value;
                //  *** Start programmer edit section *** (Операция.ПредставительКлиента Set end)

                //  *** End programmer edit section *** (Операция.ПредставительКлиента Set end)
            }
        }
        
        /// <summary>
        /// Операция.
        /// </summary>
        //  *** Start programmer edit section *** (Операция.Клиент CustomAttributes)

        //  *** End programmer edit section *** (Операция.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.WebLearning2016.Клиент Клиент
        {
            get
            {
                //  *** Start programmer edit section *** (Операция.Клиент Get start)

                //  *** End programmer edit section *** (Операция.Клиент Get start)
                IIS.WebLearning2016.Клиент result = this.fКлиент;
                //  *** Start programmer edit section *** (Операция.Клиент Get end)

                //  *** End programmer edit section *** (Операция.Клиент Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Операция.Клиент Set start)

                //  *** End programmer edit section *** (Операция.Клиент Set start)
                this.fКлиент = value;
                //  *** Start programmer edit section *** (Операция.Клиент Set end)

                //  *** End programmer edit section *** (Операция.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОперацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацияE", typeof(IIS.WebLearning2016.Операция));
                }
            }
            
            /// <summary>
            /// "ОперацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацияL", typeof(IIS.WebLearning2016.Операция));
                }
            }
        }
    }
}
