//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Очередь.
    /// </summary>
    //  *** Start programmer edit section *** (Очередь CustomAttributes)

    //  *** End programmer edit section *** (Очередь CustomAttributes)
    [BusinessServer("IIS.WebLearning2016.ОчередьBS, WebLearning2016.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОчередьE", new string[] {
            "Наименование",
            "Закрыта",
            "Актуально",
            "Тип",
            "Тип.Наименование",
            "Оператор as \'Оператор\'",
            "Оператор.ФИО",
            "Оператор.Должность",
            "Оператор.Должность.Наименование",
            "ДолжностьОператораСтр as \'Должность оператора\'"}, Hidden=new string[] {
            "Тип.Наименование",
            "Оператор.ФИО",
            "Оператор.Должность",
            "Оператор.Должность.Наименование"})]
    [AssociatedDetailViewAttribute("ОчередьE", "МестоВОчереди", "МестоВОчередиD", true, "", "Места в очереди", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОчередьE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОчередьE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОчередьL", new string[] {
            "Наименование",
            "Тип",
            "Тип.Наименование as \'Тип\'",
            "Оператор",
            "Оператор.Должность",
            "Оператор.Должность.Наименование",
            "Оператор.ФИО as \'Оператор\'",
            "ДолжностьОператораСтр as \'Должность оператора\'",
            "Закрыта",
            "Актуально"}, Hidden=new string[] {
            "Тип",
            "Оператор",
            "Оператор.Должность",
            "Оператор.Должность.Наименование"})]
    public class Очередь : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private bool fЗакрыта;
        
        private string fДолжностьОператораСтр;
        
        private bool fАктуально;
        
        private IIS.WebLearning2016.ТипОчереди fТип;
        
        private IIS.WebLearning2016.Оператор fОператор;
        
        private IIS.WebLearning2016.DetailArrayOfМестоВОчереди fМестоВОчереди;
        
        //  *** Start programmer edit section *** (Очередь CustomMembers)

        //  *** End programmer edit section *** (Очередь CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Очередь.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.Наименование Get start)

                //  *** End programmer edit section *** (Очередь.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Очередь.Наименование Get end)

                //  *** End programmer edit section *** (Очередь.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.Наименование Set start)

                //  *** End programmer edit section *** (Очередь.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Очередь.Наименование Set end)

                //  *** End programmer edit section *** (Очередь.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Закрыта.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.Закрыта CustomAttributes)

        //  *** End programmer edit section *** (Очередь.Закрыта CustomAttributes)
        public virtual bool Закрыта
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.Закрыта Get start)

                //  *** End programmer edit section *** (Очередь.Закрыта Get start)
                bool result = this.fЗакрыта;
                //  *** Start programmer edit section *** (Очередь.Закрыта Get end)

                //  *** End programmer edit section *** (Очередь.Закрыта Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.Закрыта Set start)

                //  *** End programmer edit section *** (Очередь.Закрыта Set start)
                this.fЗакрыта = value;
                //  *** Start programmer edit section *** (Очередь.Закрыта Set end)

                //  *** End programmer edit section *** (Очередь.Закрыта Set end)
            }
        }
        
        /// <summary>
        /// ДолжностьОператораСтр.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.ДолжностьОператораСтр CustomAttributes)

        //  *** End programmer edit section *** (Очередь.ДолжностьОператораСтр CustomAttributes)
        [StrLen(255)]
        public virtual string ДолжностьОператораСтр
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.ДолжностьОператораСтр Get start)

                //  *** End programmer edit section *** (Очередь.ДолжностьОператораСтр Get start)
                string result = this.fДолжностьОператораСтр;
                //  *** Start programmer edit section *** (Очередь.ДолжностьОператораСтр Get end)

                //  *** End programmer edit section *** (Очередь.ДолжностьОператораСтр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.ДолжностьОператораСтр Set start)

                //  *** End programmer edit section *** (Очередь.ДолжностьОператораСтр Set start)
                this.fДолжностьОператораСтр = value;
                //  *** Start programmer edit section *** (Очередь.ДолжностьОператораСтр Set end)

                //  *** End programmer edit section *** (Очередь.ДолжностьОператораСтр Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.Актуально CustomAttributes)

        //  *** End programmer edit section *** (Очередь.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.Актуально Get start)

                //  *** End programmer edit section *** (Очередь.Актуально Get start)
                bool result = this.fАктуально;
                //  *** Start programmer edit section *** (Очередь.Актуально Get end)

                //  *** End programmer edit section *** (Очередь.Актуально Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.Актуально Set start)

                //  *** End programmer edit section *** (Очередь.Актуально Set start)
                this.fАктуально = value;
                //  *** Start programmer edit section *** (Очередь.Актуально Set end)

                //  *** End programmer edit section *** (Очередь.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Очередь.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.Тип CustomAttributes)

        //  *** End programmer edit section *** (Очередь.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Тип"})]
        [NotNull()]
        public virtual IIS.WebLearning2016.ТипОчереди Тип
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.Тип Get start)

                //  *** End programmer edit section *** (Очередь.Тип Get start)
                IIS.WebLearning2016.ТипОчереди result = this.fТип;
                //  *** Start programmer edit section *** (Очередь.Тип Get end)

                //  *** End programmer edit section *** (Очередь.Тип Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.Тип Set start)

                //  *** End programmer edit section *** (Очередь.Тип Set start)
                this.fТип = value;
                //  *** Start programmer edit section *** (Очередь.Тип Set end)

                //  *** End programmer edit section *** (Очередь.Тип Set end)
            }
        }
        
        /// <summary>
        /// Очередь.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.Оператор CustomAttributes)

        //  *** End programmer edit section *** (Очередь.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual IIS.WebLearning2016.Оператор Оператор
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.Оператор Get start)

                //  *** End programmer edit section *** (Очередь.Оператор Get start)
                IIS.WebLearning2016.Оператор result = this.fОператор;
                //  *** Start programmer edit section *** (Очередь.Оператор Get end)

                //  *** End programmer edit section *** (Очередь.Оператор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.Оператор Set start)

                //  *** End programmer edit section *** (Очередь.Оператор Set start)
                this.fОператор = value;
                //  *** Start programmer edit section *** (Очередь.Оператор Set end)

                //  *** End programmer edit section *** (Очередь.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Очередь.
        /// </summary>
        //  *** Start programmer edit section *** (Очередь.МестоВОчереди CustomAttributes)

        //  *** End programmer edit section *** (Очередь.МестоВОчереди CustomAttributes)
        public virtual IIS.WebLearning2016.DetailArrayOfМестоВОчереди МестоВОчереди
        {
            get
            {
                //  *** Start programmer edit section *** (Очередь.МестоВОчереди Get start)

                //  *** End programmer edit section *** (Очередь.МестоВОчереди Get start)
                if ((this.fМестоВОчереди == null))
                {
                    this.fМестоВОчереди = new IIS.WebLearning2016.DetailArrayOfМестоВОчереди(this);
                }
                IIS.WebLearning2016.DetailArrayOfМестоВОчереди result = this.fМестоВОчереди;
                //  *** Start programmer edit section *** (Очередь.МестоВОчереди Get end)

                //  *** End programmer edit section *** (Очередь.МестоВОчереди Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Очередь.МестоВОчереди Set start)

                //  *** End programmer edit section *** (Очередь.МестоВОчереди Set start)
                this.fМестоВОчереди = value;
                //  *** Start programmer edit section *** (Очередь.МестоВОчереди Set end)

                //  *** End programmer edit section *** (Очередь.МестоВОчереди Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОчередьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОчередьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОчередьE", typeof(IIS.WebLearning2016.Очередь));
                }
            }
            
            /// <summary>
            /// "ОчередьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОчередьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОчередьL", typeof(IIS.WebLearning2016.Очередь));
                }
            }
        }
    }
}
