//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип клиента.
    /// </summary>
    //  *** Start programmer edit section *** (ТипКлиента CustomAttributes)

    //  *** End programmer edit section *** (ТипКлиента CustomAttributes)
    [AutoAltered()]
    [Caption("Тип клиента")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипКлиентаL", new string[] {
            "Наименование",
            "Актуально"})]
    public class ТипКлиента : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private bool fАктуально;
        
        //  *** Start programmer edit section *** (ТипКлиента CustomMembers)

        //  *** End programmer edit section *** (ТипКлиента CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (ТипКлиента.Наименование CustomAttributes)

        //  *** End programmer edit section *** (ТипКлиента.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (ТипКлиента.Наименование Get start)

                //  *** End programmer edit section *** (ТипКлиента.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (ТипКлиента.Наименование Get end)

                //  *** End programmer edit section *** (ТипКлиента.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ТипКлиента.Наименование Set start)

                //  *** End programmer edit section *** (ТипКлиента.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (ТипКлиента.Наименование Set end)

                //  *** End programmer edit section *** (ТипКлиента.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        //  *** Start programmer edit section *** (ТипКлиента.Актуально CustomAttributes)

        //  *** End programmer edit section *** (ТипКлиента.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                //  *** Start programmer edit section *** (ТипКлиента.Актуально Get start)

                //  *** End programmer edit section *** (ТипКлиента.Актуально Get start)
                bool result = this.fАктуально;
                //  *** Start programmer edit section *** (ТипКлиента.Актуально Get end)

                //  *** End programmer edit section *** (ТипКлиента.Актуально Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ТипКлиента.Актуально Set start)

                //  *** End programmer edit section *** (ТипКлиента.Актуально Set start)
                this.fАктуально = value;
                //  *** Start programmer edit section *** (ТипКлиента.Актуально Set end)

                //  *** End programmer edit section *** (ТипКлиента.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТипКлиентаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипКлиентаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипКлиентаL", typeof(IIS.WebLearning2016.ТипКлиента));
                }
            }
        }
    }
}
