//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КлиентBS.
    /// </summary>
    //  *** Start programmer edit section *** (КлиентBS CustomAttributes)

    //  *** End programmer edit section *** (КлиентBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class КлиентBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (КлиентBS CustomMembers)

        //  *** End programmer edit section *** (КлиентBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateКлиент CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateКлиент CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateКлиент(IIS.WebLearning2016.Клиент UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateКлиент)

            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateКлиент)
        }
    }
}
