//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// МестоВОчередиBS.
    /// </summary>
    //  *** Start programmer edit section *** (МестоВОчередиBS CustomAttributes)

    //  *** End programmer edit section *** (МестоВОчередиBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class МестоВОчередиBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (МестоВОчередиBS CustomMembers)

        //  *** End programmer edit section *** (МестоВОчередиBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateМестоВОчереди CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateМестоВОчереди CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateМестоВОчереди(IIS.WebLearning2016.МестоВОчереди UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateМестоВОчереди)

            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateМестоВОчереди)
        }
    }
}
