//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОперацияBS.
    /// </summary>
    //  *** Start programmer edit section *** (ОперацияBS CustomAttributes)

    //  *** End programmer edit section *** (ОперацияBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОперацияBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (ОперацияBS CustomMembers)

        //  *** End programmer edit section *** (ОперацияBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateОперация CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateОперация CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateОперация(IIS.WebLearning2016.Операция UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateОперация)

            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateОперация)
        }
    }
}
