//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WebLearning2016
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОчередьBS.
    /// </summary>
    //  *** Start programmer edit section *** (ОчередьBS CustomAttributes)

    //  *** End programmer edit section *** (ОчередьBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОчередьBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (ОчередьBS CustomMembers)

        //  *** End programmer edit section *** (ОчередьBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateОчередь CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateОчередь CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateОчередь(IIS.WebLearning2016.Очередь UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateОчередь)

            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateОчередь)
        }
    }
}
